
# MySql
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
#    password: rain1104
    password: rain

server:
  port=80